apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: dbp-demo-aci
  name: dbp-demo-aci
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: dbp-demo-aci
    spec:
      containers:
        - name: dbp-demo-aci
          image: avknsk/dbp-demo-aci
      nodeName: aci-connector    
