apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: dbp-demo
  name: dbp-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dbp-demo
    spec:
      containers:
        - name: dbp-demo
          image: dbpdemo.azurecr.io/dbp-demo:v1.0
          ports:
            - containerPort: 5000
              protocol: TCP