apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbp-demo
  name: dbp-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: dbp-demo
  type: LoadBalancer